### ISSUE TITLE
Tracking issue: Supported trade types

### ISSUE THREAD

**Issue by Sliman4** [INTEARnear/trade-indexer#1]
- [x] Ref
- [x] Ref multi-step
- [x] Ref arbitrage
- [x] Ref stableswap
- [x] Ref rated
- [x] Ref DCL
- [ ] Ref limit order (is this the same as DCL?)
- [x] Ref dragonbot
- [x] Ref DELEGATE
- [ ] Veax (does anyone use this?)
- [ ] ~~Orderly spot~~ (left NEAR)
- [ ] Spin (spot) (does anyone use this?)
- [ ] Jumbo (does anyone use this?)
- [x] ref.hot.tg
